### ISSUE TITLE
Error when trying to use the website on Firefox

### ISSUE THREAD

**Issue by elihschiff** [rcos/rcos-automation#11]
When I go to https://rcos-discord.herokuapp.com on on Firefox (84.0.1 on arch linux) I get this error

![image](https://user-images.githubusercontent.com/18558130/103179737-fafce180-485c-11eb-92db-34f5e27c3d96.png)

There are also come console errors that might be related. I tested this in an incognito tab as well
![image](https://user-images.githubusercontent.com/18558130/103179753-2e3f7080-485d-11eb-8a72-05e4ceb4d3e0.png)

**Comment by Apexal** [comment]
Thank you for catching this! I don't believe I properly refresh the access tokens for Discord. I'll fix this ASAP.

**Comment by Apexal** [comment]
I'll be rewriting this to use the new internal RCOS API to connect user accounts, and ensure we have a user record of every student/faculty.

**Comment by Apexal** [comment]
Closing since this program is being deprecated.
